version: '3'
services:

  pagerbeauty:
    build: .
    image: "sergiitk/pagerbeauty"
    command: ["yarn", "app:watch"]
    ports:
      - "8080:8080"
    env_file:
      - .env
    volumes:
      - .:/usr/src/app/

  sut:
    build:
      context: .
      dockerfile: ./Dockerfile-test
