version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10.12.0-stretch
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          key: v1-dependencies-{{ checksum "yarn.lock" }}
      - run:
          name: Install dependencies
          command: yarn install --frozen-lockfile
      - save_cache:
          key: v1-dependencies-{{ checksum "yarn.lock" }}
          paths:
            - node_modules

  lint:
    docker:
      - image: circleci/node:10.12.0-stretch
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          key: v1-dependencies-{{ checksum "yarn.lock" }}
      - run:
          name: Lint
          command: yarn lint

  test:
    docker:
      - image: circleci/node:10.12.0-stretch
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          key: v1-dependencies-{{ checksum "yarn.lock" }}
      - run:
          name: Test
          command: yarn test:full

  semantic-release:
    docker:
      - image: circleci/node:10.12.0-stretch
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          key: v1-dependencies-{{ checksum "yarn.lock" }}
      - run:
          name: Release!
          command: yarn run semantic-release --debug

workflows:
  version: 2
  build-test-release:
    jobs:
      - build
      - lint:
          requires:
            - build
      - test:
          requires:
            - build
      - semantic-release:
          requires:
            - lint
            - test
