version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10.11.0-stretch
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-
      - run:
          name: Install dependencies
          command: yarn install
      - save_cache:
          key: v1-dependencies-{{ checksum "package.json" }}
          paths:
            - node_modules
  lint:
    docker:
      - image: circleci/node:10.11.0-stretch
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Lint
          command: yarn lint
  test:
    docker:
      - image: circleci/node:10.11.0-stretch
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Test
          command: yarn test:full
workflows:
  version: 2
  build-and-test:
    jobs:
      - build
      - lint:
          requires:
            - build
      - test:
          requires:
            - build
